---

fixtures:
  # make your own module available for the test runs
  symlinks:
    solr: "#{source_dir}"
  # dependencies from git
  repositories:
    apt: 'git://github.com/puppetlabs/puppetlabs-apt.git'
  # dependencies from puppetforge
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.12.0'
    archive:  
      repo: 'puppet/archive'
      ref: '3.2.1'
